# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - "main"
    tags: 
      - "**"

  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout/@v4

        - name: Make Docker Metadata
          id: metadata
          uses: docker/metadata-action@v5
          with:
            images: ${{ github.repository }}

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ github.repository_owner }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            platforms: linux/amd64,linux/arm64
            tags: ${{ steps.metadata.outputs.tags }}
            labels: ${{ steps.metadata.outputs.labels }}