# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      api_breakage_check_enabled: false
      format_check_enabled: false
      unacceptable_language_check_enabled: false
      license_header_check_enabled: false
      broken_symlink_check_enabled: false
      shell_check_enabled: false
      yamllint_check_enabled: false
      python_lint_check_enabled: false
      license_header_check_project_name: "Netbot"
      linux_pre_build_command: |
        'git config --global url."https://${{ github.token }}@github".insteadOf https://github && cat ~/.gitconfig'
